### ISSUE TITLE
Change input file from txt to yaml

### ISSUE THREAD

**Issue by praveenperera** [candostyavuz/magma#1]
```yaml
chain_type: ETH
api_methods: 
  - getProof
  - name: getStorageAt
    args: 2
```
